[package]
name = "what-to-watch-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = {version = "0.14.20", features = ["full"]}
tokio = {version = "1.21.1", features = ["full"]}
