version: "2.0"
services:
  app:
    image: ubuntu
    volumes:
      - ${HOME}/what-to-watch-bot:/what-to-watch-bot
    ports:
      - 3000:3000
    command: bash -c "chmod +x /what-to-watch-bot && /what-to-watch-bot"