name: build
on:
  workflow_call:
    secrets:
      ARCH:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ secrets.ARCH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install arch
        run: rustup target add ${ARCH}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${ARCH}
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: target/release/what-to-watch-bot